spring.application.name=demo
server.port=8081
server.data.mongodb.host=loacalhost
server.data.mongodb.port=27017
server.data.mongodb.datbase=journaldb
# server.data.mongodb.username=myjournaluser
# server.data.mongodb.password=mypassword
